# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1792, 986)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_left = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_left.setMinimumSize(QtCore.QSize(250, 0))
        self.tab_left.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tab_left.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_left.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_left.setObjectName("tab_left")
        self.com_tab = QtWidgets.QWidget()
        self.com_tab.setObjectName("com_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.com_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.com_tab)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.com_combo = QtWidgets.QComboBox(self.com_tab)
        self.com_combo.setObjectName("com_combo")
        self.verticalLayout_2.addWidget(self.com_combo)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.com_info_icon_label_new_connect = QtWidgets.QLabel(self.com_tab)
        self.com_info_icon_label_new_connect.setMinimumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label_new_connect.setMaximumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label_new_connect.setText("")
        self.com_info_icon_label_new_connect.setObjectName("com_info_icon_label_new_connect")
        self.horizontalLayout_5.addWidget(self.com_info_icon_label_new_connect)
        self.com_info_label_new_connect = QtWidgets.QLabel(self.com_tab)
        self.com_info_label_new_connect.setMaximumSize(QtCore.QSize(16777215, 16))
        self.com_info_label_new_connect.setText("")
        self.com_info_label_new_connect.setObjectName("com_info_label_new_connect")
        self.horizontalLayout_5.addWidget(self.com_info_label_new_connect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_17 = QtWidgets.QLabel(self.com_tab)
        self.label_17.setMinimumSize(QtCore.QSize(0, 20))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.baud_rate_combo = QtWidgets.QComboBox(self.com_tab)
        self.baud_rate_combo.setObjectName("baud_rate_combo")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.verticalLayout_2.addWidget(self.baud_rate_combo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.com_btn = QtWidgets.QPushButton(self.com_tab)
        self.com_btn.setObjectName("com_btn")
        self.verticalLayout.addWidget(self.com_btn)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.com_info_icon_label = QtWidgets.QLabel(self.com_tab)
        self.com_info_icon_label.setMinimumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label.setMaximumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label.setText("")
        self.com_info_icon_label.setObjectName("com_info_icon_label")
        self.horizontalLayout_4.addWidget(self.com_info_icon_label)
        self.com_info_label = QtWidgets.QLabel(self.com_tab)
        self.com_info_label.setMaximumSize(QtCore.QSize(16777215, 16))
        self.com_info_label.setText("")
        self.com_info_label.setObjectName("com_info_label")
        self.horizontalLayout_4.addWidget(self.com_info_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupBox_3 = QtWidgets.QGroupBox(self.com_tab)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tab_left.addTab(self.com_tab, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.data_type_btn_groupBox = QtWidgets.QGroupBox(self.tab_12)
        self.data_type_btn_groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.data_type_btn_groupBox.setFlat(True)
        self.data_type_btn_groupBox.setCheckable(False)
        self.data_type_btn_groupBox.setObjectName("data_type_btn_groupBox")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.data_type_btn_groupBox)
        self.gridLayout_38.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_38.setSpacing(0)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.data_type_btn_layout = QtWidgets.QVBoxLayout()
        self.data_type_btn_layout.setObjectName("data_type_btn_layout")
        self.gridLayout_38.addLayout(self.data_type_btn_layout, 0, 0, 1, 1)
        self.verticalLayout_20.addWidget(self.data_type_btn_groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.all_data_type_vLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.all_data_type_vLayout.setContentsMargins(2, 2, 2, 2)
        self.all_data_type_vLayout.setObjectName("all_data_type_vLayout")
        self.data_type_select_counter_label = QtWidgets.QLabel(self.groupBox_4)
        self.data_type_select_counter_label.setObjectName("data_type_select_counter_label")
        self.all_data_type_vLayout.addWidget(self.data_type_select_counter_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 26))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("padding-top: 0px; padding-bottom: 0px;")
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_2.setAcceptRichText(False)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setMaximumSize(QtCore.QSize(26, 26))
        font = QtGui.QFont()
        font.setKerning(False)
        self.pushButton.setFont(font)
        self.pushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.all_data_type_vLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_20.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_17.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_17.addWidget(self.textBrowser)
        self.verticalLayout_20.addWidget(self.groupBox)
        self.data_type_update_btn = QtWidgets.QPushButton(self.tab_12)
        self.data_type_update_btn.setObjectName("data_type_update_btn")
        self.verticalLayout_20.addWidget(self.data_type_update_btn)
        self.horizontalLayout_3.addLayout(self.verticalLayout_20)
        self.tab_left.addTab(self.tab_12, "")
        self.gridLayout.addWidget(self.tab_left, 0, 0, 2, 1)
        self.tab_right = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_right.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_right.setTabsClosable(False)
        self.tab_right.setObjectName("tab_right")
        self.data_tab_right = QtWidgets.QWidget()
        self.data_tab_right.setObjectName("data_tab_right")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.data_tab_right)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.data_tab_right)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1049, 564))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.data_tab_right_gridLayout = QtWidgets.QGridLayout()
        self.data_tab_right_gridLayout.setObjectName("data_tab_right_gridLayout")
        self.data4_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data4_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.data4_label.setObjectName("data4_label")
        self.data_tab_right_gridLayout.addWidget(self.data4_label, 2, 1, 1, 1)
        self.data3_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data3_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.data3_label.setObjectName("data3_label")
        self.data_tab_right_gridLayout.addWidget(self.data3_label, 2, 0, 1, 1)
        self.data2_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data2_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.data2_label.setObjectName("data2_label")
        self.data_tab_right_gridLayout.addWidget(self.data2_label, 0, 1, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.x2_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x2_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.x2_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.x2_lcd.setSmallDecimalPoint(True)
        self.x2_lcd.setDigitCount(10)
        self.x2_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x2_lcd.setProperty("value", 0.0)
        self.x2_lcd.setObjectName("x2_lcd")
        self.gridLayout_14.addWidget(self.x2_lcd, 0, 1, 1, 1)
        self.y2_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.y2_sub_label_lcd.setFont(font)
        self.y2_sub_label_lcd.setObjectName("y2_sub_label_lcd")
        self.gridLayout_14.addWidget(self.y2_sub_label_lcd, 1, 0, 1, 1)
        self.z2_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z2_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.z2_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.z2_lcd.setSmallDecimalPoint(True)
        self.z2_lcd.setDigitCount(10)
        self.z2_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z2_lcd.setProperty("value", 0.0)
        self.z2_lcd.setObjectName("z2_lcd")
        self.gridLayout_14.addWidget(self.z2_lcd, 2, 1, 1, 1)
        self.y2_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y2_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.y2_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.y2_lcd.setSmallDecimalPoint(True)
        self.y2_lcd.setDigitCount(10)
        self.y2_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y2_lcd.setProperty("value", 0.0)
        self.y2_lcd.setObjectName("y2_lcd")
        self.gridLayout_14.addWidget(self.y2_lcd, 1, 1, 1, 1)
        self.x2_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.x2_sub_label_lcd.setFont(font)
        self.x2_sub_label_lcd.setObjectName("x2_sub_label_lcd")
        self.gridLayout_14.addWidget(self.x2_sub_label_lcd, 0, 0, 1, 1)
        self.z2_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.z2_sub_label_lcd.setFont(font)
        self.z2_sub_label_lcd.setObjectName("z2_sub_label_lcd")
        self.gridLayout_14.addWidget(self.z2_sub_label_lcd, 2, 0, 1, 1)
        self.gridLayout_14.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_14, 1, 1, 1, 1)
        self.data1_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data1_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.data1_label.setObjectName("data1_label")
        self.data_tab_right_gridLayout.addWidget(self.data1_label, 0, 0, 1, 1)
        self.gridLayout_data4 = QtWidgets.QGridLayout()
        self.gridLayout_data4.setObjectName("gridLayout_data4")
        self.y4_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.y4_sub_label_lcd.setFont(font)
        self.y4_sub_label_lcd.setObjectName("y4_sub_label_lcd")
        self.gridLayout_data4.addWidget(self.y4_sub_label_lcd, 1, 0, 1, 1)
        self.z4_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z4_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.z4_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.z4_lcd.setSmallDecimalPoint(True)
        self.z4_lcd.setDigitCount(10)
        self.z4_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z4_lcd.setProperty("value", 0.0)
        self.z4_lcd.setObjectName("z4_lcd")
        self.gridLayout_data4.addWidget(self.z4_lcd, 2, 1, 1, 1)
        self.z4_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.z4_sub_label_lcd.setFont(font)
        self.z4_sub_label_lcd.setObjectName("z4_sub_label_lcd")
        self.gridLayout_data4.addWidget(self.z4_sub_label_lcd, 2, 0, 1, 1)
        self.y4_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y4_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.y4_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.y4_lcd.setSmallDecimalPoint(True)
        self.y4_lcd.setDigitCount(10)
        self.y4_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y4_lcd.setProperty("value", 0.0)
        self.y4_lcd.setObjectName("y4_lcd")
        self.gridLayout_data4.addWidget(self.y4_lcd, 1, 1, 1, 1)
        self.x4_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.x4_sub_label_lcd.setFont(font)
        self.x4_sub_label_lcd.setObjectName("x4_sub_label_lcd")
        self.gridLayout_data4.addWidget(self.x4_sub_label_lcd, 0, 0, 1, 1)
        self.x4_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x4_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.x4_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.x4_lcd.setSmallDecimalPoint(True)
        self.x4_lcd.setDigitCount(10)
        self.x4_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x4_lcd.setProperty("value", 0.0)
        self.x4_lcd.setObjectName("x4_lcd")
        self.gridLayout_data4.addWidget(self.x4_lcd, 0, 1, 1, 1)
        self.gridLayout_data4.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_data4, 3, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.y3_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.y3_sub_label_lcd.setFont(font)
        self.y3_sub_label_lcd.setObjectName("y3_sub_label_lcd")
        self.gridLayout_7.addWidget(self.y3_sub_label_lcd, 1, 0, 1, 1)
        self.z3_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z3_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.z3_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.z3_lcd.setSmallDecimalPoint(True)
        self.z3_lcd.setDigitCount(10)
        self.z3_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z3_lcd.setProperty("value", 0.0)
        self.z3_lcd.setObjectName("z3_lcd")
        self.gridLayout_7.addWidget(self.z3_lcd, 2, 1, 1, 1)
        self.z3_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.z3_sub_label_lcd.setFont(font)
        self.z3_sub_label_lcd.setObjectName("z3_sub_label_lcd")
        self.gridLayout_7.addWidget(self.z3_sub_label_lcd, 2, 0, 1, 1)
        self.y3_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y3_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.y3_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.y3_lcd.setSmallDecimalPoint(True)
        self.y3_lcd.setDigitCount(10)
        self.y3_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y3_lcd.setProperty("value", 0.0)
        self.y3_lcd.setObjectName("y3_lcd")
        self.gridLayout_7.addWidget(self.y3_lcd, 1, 1, 1, 1)
        self.x3_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.x3_sub_label_lcd.setFont(font)
        self.x3_sub_label_lcd.setObjectName("x3_sub_label_lcd")
        self.gridLayout_7.addWidget(self.x3_sub_label_lcd, 0, 0, 1, 1)
        self.x3_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x3_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.x3_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.x3_lcd.setSmallDecimalPoint(True)
        self.x3_lcd.setDigitCount(10)
        self.x3_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x3_lcd.setProperty("value", 0.0)
        self.x3_lcd.setObjectName("x3_lcd")
        self.gridLayout_7.addWidget(self.x3_lcd, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_7, 3, 0, 1, 1)
        self.gridLayout_data1 = QtWidgets.QGridLayout()
        self.gridLayout_data1.setObjectName("gridLayout_data1")
        self.z1_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.z1_sub_label_lcd.setFont(font)
        self.z1_sub_label_lcd.setObjectName("z1_sub_label_lcd")
        self.gridLayout_data1.addWidget(self.z1_sub_label_lcd, 2, 0, 1, 1)
        self.x1_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.x1_sub_label_lcd.setFont(font)
        self.x1_sub_label_lcd.setObjectName("x1_sub_label_lcd")
        self.gridLayout_data1.addWidget(self.x1_sub_label_lcd, 0, 0, 1, 1)
        self.y1_sub_label_lcd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.y1_sub_label_lcd.setFont(font)
        self.y1_sub_label_lcd.setObjectName("y1_sub_label_lcd")
        self.gridLayout_data1.addWidget(self.y1_sub_label_lcd, 1, 0, 1, 1)
        self.z1_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z1_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.z1_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.z1_lcd.setSmallDecimalPoint(True)
        self.z1_lcd.setDigitCount(10)
        self.z1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z1_lcd.setProperty("value", 0.0)
        self.z1_lcd.setObjectName("z1_lcd")
        self.gridLayout_data1.addWidget(self.z1_lcd, 2, 1, 1, 1)
        self.y1_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y1_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.y1_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.y1_lcd.setSmallDecimalPoint(True)
        self.y1_lcd.setDigitCount(10)
        self.y1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y1_lcd.setProperty("value", 0.0)
        self.y1_lcd.setObjectName("y1_lcd")
        self.gridLayout_data1.addWidget(self.y1_lcd, 1, 1, 1, 1)
        self.x1_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x1_lcd.setMinimumSize(QtCore.QSize(0, 70))
        self.x1_lcd.setMaximumSize(QtCore.QSize(16777215, 70))
        self.x1_lcd.setSmallDecimalPoint(True)
        self.x1_lcd.setDigitCount(10)
        self.x1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x1_lcd.setProperty("value", 0.0)
        self.x1_lcd.setObjectName("x1_lcd")
        self.gridLayout_data1.addWidget(self.x1_lcd, 0, 1, 1, 1)
        self.gridLayout_data1.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_data1, 1, 0, 1, 1)
        self.data_tab_right_gridLayout.setRowStretch(1, 1)
        self.data_tab_right_gridLayout.setRowStretch(3, 1)
        self.verticalLayout_15.addLayout(self.data_tab_right_gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tab_right.addTab(self.data_tab_right, "")
        self.graph_tab_right = QtWidgets.QWidget()
        self.graph_tab_right.setObjectName("graph_tab_right")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.graph_tab_right)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.graph_tab_time_scrollArea = QtWidgets.QScrollArea(self.graph_tab_right)
        self.graph_tab_time_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graph_tab_time_scrollArea.setWidgetResizable(True)
        self.graph_tab_time_scrollArea.setObjectName("graph_tab_time_scrollArea")
        self.graph_tab_right_layout = QtWidgets.QWidget()
        self.graph_tab_right_layout.setGeometry(QtCore.QRect(0, 0, 1049, 564))
        self.graph_tab_right_layout.setObjectName("graph_tab_right_layout")
        self.graph_tab_time_scrollArea.setWidget(self.graph_tab_right_layout)
        self.verticalLayout_12.addWidget(self.graph_tab_time_scrollArea)
        self.tab_right.addTab(self.graph_tab_right, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.graph_tab_freq_scrollArea = QtWidgets.QScrollArea(self.tab)
        self.graph_tab_freq_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graph_tab_freq_scrollArea.setWidgetResizable(True)
        self.graph_tab_freq_scrollArea.setObjectName("graph_tab_freq_scrollArea")
        self.graph_tab_right_layout_2 = QtWidgets.QWidget()
        self.graph_tab_right_layout_2.setGeometry(QtCore.QRect(0, 0, 1049, 564))
        self.graph_tab_right_layout_2.setObjectName("graph_tab_right_layout_2")
        self.graph_tab_freq_scrollArea.setWidget(self.graph_tab_right_layout_2)
        self.verticalLayout_13.addWidget(self.graph_tab_freq_scrollArea)
        self.tab_right.addTab(self.tab, "")
        self.vcom_tab_right = QtWidgets.QWidget()
        self.vcom_tab_right.setObjectName("vcom_tab_right")
        self.tab_right.addTab(self.vcom_tab_right, "")
        self.gridLayout.addWidget(self.tab_right, 0, 1, 1, 1)
        self.tab_down_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_down_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tab_down_2.setTabPosition(QtWidgets.QTabWidget.South)
        self.tab_down_2.setDocumentMode(True)
        self.tab_down_2.setObjectName("tab_down_2")
        self.tab_94 = QtWidgets.QWidget()
        self.tab_94.setObjectName("tab_94")
        self.gridLayout_74 = QtWidgets.QGridLayout(self.tab_94)
        self.gridLayout_74.setObjectName("gridLayout_74")
        self.tab_down_4 = QtWidgets.QTabWidget(self.tab_94)
        self.tab_down_4.setUsesScrollButtons(True)
        self.tab_down_4.setTabsClosable(False)
        self.tab_down_4.setObjectName("tab_down_4")
        self.com_tab_down_8 = QtWidgets.QWidget()
        self.com_tab_down_8.setObjectName("com_tab_down_8")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.com_tab_down_8)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.port_console_textEdit = QtWidgets.QTextEdit(self.com_tab_down_8)
        self.port_console_textEdit.setObjectName("port_console_textEdit")
        self.verticalLayout_39.addWidget(self.port_console_textEdit)
        self.tab_down_4.addTab(self.com_tab_down_8, "")
        self.warning_tab_down_4 = QtWidgets.QWidget()
        self.warning_tab_down_4.setObjectName("warning_tab_down_4")
        self.tab_down_4.addTab(self.warning_tab_down_4, "")
        self.data_tab_down_4 = QtWidgets.QWidget()
        self.data_tab_down_4.setObjectName("data_tab_down_4")
        self.gridLayout_82 = QtWidgets.QGridLayout(self.data_tab_down_4)
        self.gridLayout_82.setObjectName("gridLayout_82")
        self.widget_4 = QtWidgets.QWidget(self.data_tab_down_4)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_83 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_83.setObjectName("gridLayout_83")
        self.gridLayout_82.addWidget(self.widget_4, 0, 0, 1, 1)
        self.tab_down_4.addTab(self.data_tab_down_4, "")
        self.gridLayout_74.addWidget(self.tab_down_4, 0, 0, 1, 1)
        self.tab_down_2.addTab(self.tab_94, "")
        self.tab_121 = QtWidgets.QWidget()
        self.tab_121.setObjectName("tab_121")
        self.gridLayout_93 = QtWidgets.QGridLayout(self.tab_121)
        self.gridLayout_93.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_93.setObjectName("gridLayout_93")
        self.frame_27 = QtWidgets.QFrame(self.tab_121)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_94 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_94.setObjectName("gridLayout_94")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.line_13 = QtWidgets.QFrame(self.frame_27)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_48.addWidget(self.line_13)
        self.line_14 = QtWidgets.QFrame(self.frame_27)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_48.addWidget(self.line_14)
        self.line_15 = QtWidgets.QFrame(self.frame_27)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_48.addWidget(self.line_15)
        self.gridLayout_94.addLayout(self.verticalLayout_48, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_16 = QtWidgets.QFrame(self.frame_27)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.horizontalLayout_7.addWidget(self.line_16)
        self.line_17 = QtWidgets.QFrame(self.frame_27)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_7.addWidget(self.line_17)
        self.line_18 = QtWidgets.QFrame(self.frame_27)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_7.addWidget(self.line_18)
        self.gridLayout_94.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.gridLayout_94.setColumnStretch(0, 1)
        self.gridLayout_94.setColumnStretch(1, 1)
        self.gridLayout_93.addWidget(self.frame_27, 0, 0, 1, 1)
        self.tab_down_2.addTab(self.tab_121, "")
        self.tab_122 = QtWidgets.QWidget()
        self.tab_122.setObjectName("tab_122")
        self.gridLayout_95 = QtWidgets.QGridLayout(self.tab_122)
        self.gridLayout_95.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_95.setObjectName("gridLayout_95")
        self.tab_down_2.addTab(self.tab_122, "")
        self.tab_123 = QtWidgets.QWidget()
        self.tab_123.setObjectName("tab_123")
        self.tab_down_2.addTab(self.tab_123, "")
        self.tab_124 = QtWidgets.QWidget()
        self.tab_124.setObjectName("tab_124")
        self.tab_down_2.addTab(self.tab_124, "")
        self.gridLayout.addWidget(self.tab_down_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_vertical = QtWidgets.QToolBar(MainWindow)
        self.toolBar_vertical.setObjectName("toolBar_vertical")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_vertical)
        self.help_dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.help_dockWidget.setObjectName("help_dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.textEdit = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_26.addWidget(self.textEdit, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_26.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.help_dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.help_dockWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1792, 24))
        self.menubar.setObjectName("menubar")
        self.menuStyles = QtWidgets.QMenu(self.menubar)
        self.menuStyles.setObjectName("menuStyles")
        self.menuMenu_with_icons = QtWidgets.QMenu(self.menubar)
        self.menuMenu_with_icons.setObjectName("menuMenu_with_icons")
        self.menumenu2 = QtWidgets.QMenu(self.menubar)
        self.menumenu2.setObjectName("menumenu2")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        self.menuSubmenu = QtWidgets.QMenu(self.menumenu)
        self.menuSubmenu.setObjectName("menuSubmenu")
        self.menuDensity = QtWidgets.QMenu(self.menubar)
        self.menuDensity.setObjectName("menuDensity")
        self.menuMenu3 = QtWidgets.QMenu(self.menubar)
        self.menuMenu3.setObjectName("menuMenu3")
        self.menumenu_disabled = QtWidgets.QMenu(self.menubar)
        self.menumenu_disabled.setEnabled(False)
        self.menumenu_disabled.setObjectName("menumenu_disabled")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_6 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_6.setEnabled(False)
        self.dockWidget_6.setMinimumSize(QtCore.QSize(0, 16))
        self.dockWidget_6.setMaximumSize(QtCore.QSize(0, 16))
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents_5)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.listWidget.addItem(item)
        self.gridLayout_20.addWidget(self.listWidget, 0, 0, 1, 1)
        self.dockWidget_6.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_6)
        self.actionSubmenu_2 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_2.setCheckable(True)
        self.actionSubmenu_2.setObjectName("actionSubmenu_2")
        self.actionSubmenu_3 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_3.setObjectName("actionSubmenu_3")
        self.actionSUBSUB = QtWidgets.QAction(MainWindow)
        self.actionSUBSUB.setObjectName("actionSUBSUB")
        self.actionSUBSUB_2 = QtWidgets.QAction(MainWindow)
        self.actionSUBSUB_2.setObjectName("actionSUBSUB_2")
        self.actionSUBSUB_3 = QtWidgets.QAction(MainWindow)
        self.actionSUBSUB_3.setObjectName("actionSUBSUB_3")
        self.actiondissabled = QtWidgets.QAction(MainWindow)
        self.actiondissabled.setEnabled(False)
        self.actiondissabled.setObjectName("actiondissabled")
        self.actionSubmenu = QtWidgets.QAction(MainWindow)
        self.actionSubmenu.setCheckable(True)
        self.actionSubmenu.setChecked(True)
        self.actionSubmenu.setObjectName("actionSubmenu")
        self.actionSubmenu_4 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_4.setCheckable(True)
        self.actionSubmenu_4.setObjectName("actionSubmenu_4")
        self.actionSubmenu_5 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_5.setCheckable(True)
        self.actionSubmenu_5.setEnabled(False)
        self.actionSubmenu_5.setObjectName("actionSubmenu_5")
        self.actionToolbar = QtWidgets.QAction(MainWindow)
        self.actionToolbar.setObjectName("actionToolbar")
        self.actionSelected = QtWidgets.QAction(MainWindow)
        self.actionSelected.setCheckable(True)
        self.actionSelected.setChecked(True)
        self.actionSelected.setObjectName("actionSelected")
        self.test_action = QtWidgets.QAction(MainWindow)
        self.test_action.setObjectName("test_action")
        self.test_action_2 = QtWidgets.QAction(MainWindow)
        self.test_action_2.setObjectName("test_action_2")
        self.actionaction3 = QtWidgets.QAction(MainWindow)
        self.actionaction3.setObjectName("actionaction3")
        self.action111 = QtWidgets.QAction(MainWindow)
        self.action111.setCheckable(True)
        self.action111.setObjectName("action111")
        self.action222 = QtWidgets.QAction(MainWindow)
        self.action222.setCheckable(True)
        self.action222.setObjectName("action222")
        self.action333 = QtWidgets.QAction(MainWindow)
        self.action333.setCheckable(True)
        self.action333.setObjectName("action333")
        self.actionsubmenu = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionsubmenu.setIcon(icon)
        self.actionsubmenu.setObjectName("actionsubmenu")
        self.actionsubmenu_2 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("folder")
        self.actionsubmenu_2.setIcon(icon)
        self.actionsubmenu_2.setObjectName("actionsubmenu_2")
        self.actionsubmenu_3 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionsubmenu_3.setIcon(icon)
        self.actionsubmenu_3.setObjectName("actionsubmenu_3")
        self.actionsubmenu_4 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionsubmenu_4.setIcon(icon)
        self.actionsubmenu_4.setObjectName("actionsubmenu_4")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.toolBar.addAction(self.actionToolbar)
        self.toolBar.addAction(self.actionSelected)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.test_action)
        self.toolBar.addAction(self.test_action_2)
        self.toolBar.addAction(self.actionaction3)
        self.toolBar_vertical.addAction(self.actionToolbar)
        self.toolBar_vertical.addAction(self.actionSelected)
        self.menuMenu_with_icons.addAction(self.actionsubmenu)
        self.menuMenu_with_icons.addAction(self.actionsubmenu_2)
        self.menuMenu_with_icons.addSeparator()
        self.menuMenu_with_icons.addAction(self.actionsubmenu_4)
        self.menuMenu_with_icons.addAction(self.actionsubmenu_3)
        self.menuMenu_with_icons.addAction(self.actionSave_all)
        self.menuMenu_with_icons.addSeparator()
        self.menuMenu_with_icons.addAction(self.actionClose)
        self.menumenu2.addAction(self.actionSubmenu)
        self.menumenu2.addAction(self.actionSubmenu_4)
        self.menumenu2.addAction(self.actionSubmenu_5)
        self.menuSubmenu.addAction(self.actionSUBSUB)
        self.menuSubmenu.addAction(self.actionSUBSUB_2)
        self.menuSubmenu.addSeparator()
        self.menuSubmenu.addAction(self.actionSUBSUB_3)
        self.menumenu.addAction(self.menuSubmenu.menuAction())
        self.menumenu.addAction(self.actionSubmenu_2)
        self.menumenu.addSeparator()
        self.menumenu.addAction(self.actionSubmenu_3)
        self.menumenu.addAction(self.actiondissabled)
        self.menubar.addAction(self.menuDensity.menuAction())
        self.menubar.addAction(self.menumenu.menuAction())
        self.menubar.addAction(self.menumenu2.menuAction())
        self.menubar.addAction(self.menuMenu_with_icons.menuAction())
        self.menubar.addAction(self.menumenu_disabled.menuAction())
        self.menubar.addAction(self.menuMenu3.menuAction())
        self.menubar.addAction(self.menuStyles.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_left.setCurrentIndex(1)
        self.tab_right.setCurrentIndex(1)
        self.tab_down_2.setCurrentIndex(0)
        self.tab_down_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tab_right, self.listWidget)
        MainWindow.setTabOrder(self.listWidget, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.plainTextEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qt Material"))
        self.label_18.setText(_translate("MainWindow", "端口号"))
        self.label_17.setText(_translate("MainWindow", "波特率"))
        self.baud_rate_combo.setItemText(0, _translate("MainWindow", "2400"))
        self.baud_rate_combo.setItemText(1, _translate("MainWindow", "4800"))
        self.baud_rate_combo.setItemText(2, _translate("MainWindow", "9600"))
        self.baud_rate_combo.setItemText(3, _translate("MainWindow", "19200"))
        self.baud_rate_combo.setItemText(4, _translate("MainWindow", "38400"))
        self.baud_rate_combo.setItemText(5, _translate("MainWindow", "57600"))
        self.baud_rate_combo.setItemText(6, _translate("MainWindow", "115200"))
        self.baud_rate_combo.setItemText(7, _translate("MainWindow", "230400"))
        self.com_btn.setText(_translate("MainWindow", "启动"))
        self.groupBox_3.setTitle(_translate("MainWindow", "串口设置"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.tab_left.setTabText(self.tab_left.indexOf(self.com_tab), _translate("MainWindow", "串口"))
        self.data_type_btn_groupBox.setTitle(_translate("MainWindow", "已展示"))
        self.data_type_btn_groupBox.setProperty("class", _translate("MainWindow", "fill_background"))
        self.groupBox_4.setTitle(_translate("MainWindow", "所有"))
        self.groupBox_4.setProperty("class", _translate("MainWindow", "fill_background"))
        self.data_type_select_counter_label.setText(_translate("MainWindow", "已选取0个数据项"))
        self.groupBox.setTitle(_translate("MainWindow", "详情"))
        self.data_type_update_btn.setText(_translate("MainWindow", "更新"))
        self.tab_left.setTabText(self.tab_left.indexOf(self.tab_12), _translate("MainWindow", "数据"))
        self.data4_label.setText(_translate("MainWindow", "data4"))
        self.data3_label.setText(_translate("MainWindow", "data3"))
        self.data2_label.setText(_translate("MainWindow", "data2"))
        self.y2_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.x2_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.z2_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.data1_label.setText(_translate("MainWindow", "data1"))
        self.y4_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.z4_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.x4_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.y3_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.z3_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.x3_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.z1_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.x1_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.y1_sub_label_lcd.setText(_translate("MainWindow", "? "))
        self.tab_right.setTabText(self.tab_right.indexOf(self.data_tab_right), _translate("MainWindow", "实时监视"))
        self.tab_right.setTabText(self.tab_right.indexOf(self.graph_tab_right), _translate("MainWindow", "时域"))
        self.tab_right.setTabText(self.tab_right.indexOf(self.tab), _translate("MainWindow", "频域"))
        self.tab_right.setTabText(self.tab_right.indexOf(self.vcom_tab_right), _translate("MainWindow", "模拟单片机"))
        self.tab_down_4.setTabText(self.tab_down_4.indexOf(self.com_tab_down_8), _translate("MainWindow", "串口"))
        self.tab_down_4.setTabText(self.tab_down_4.indexOf(self.warning_tab_down_4), _translate("MainWindow", "警告"))
        self.tab_down_4.setTabText(self.tab_down_4.indexOf(self.data_tab_down_4), _translate("MainWindow", "数据"))
        self.tab_down_2.setTabText(self.tab_down_2.indexOf(self.tab_94), _translate("MainWindow", "Page"))
        self.tab_down_2.setTabText(self.tab_down_2.indexOf(self.tab_121), _translate("MainWindow", "Lines"))
        self.tab_down_2.setTabText(self.tab_down_2.indexOf(self.tab_122), _translate("MainWindow", "Page"))
        self.tab_down_2.setTabText(self.tab_down_2.indexOf(self.tab_123), _translate("MainWindow", "Page"))
        self.tab_down_2.setTabText(self.tab_down_2.indexOf(self.tab_124), _translate("MainWindow", "Long Page Name"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_vertical.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.help_dockWidget.setWindowTitle(_translate("MainWindow", "说明书"))
        self.textEdit.setMarkdown(_translate("MainWindow", "欢迎使用上位机\n"
"\n"
""))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">欢迎使用上位机</p></body></html>"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "请配置串口"))
        self.menuStyles.setTitle(_translate("MainWindow", "风格"))
        self.menuMenu_with_icons.setTitle(_translate("MainWindow", "Menu with icons"))
        self.menumenu2.setTitle(_translate("MainWindow", "Menu2"))
        self.menumenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuSubmenu.setTitle(_translate("MainWindow", "Submenu"))
        self.menuDensity.setTitle(_translate("MainWindow", "Density"))
        self.menuMenu3.setTitle(_translate("MainWindow", "Menu4"))
        self.menumenu_disabled.setTitle(_translate("MainWindow", "Menu3 disabled"))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "Top Dock"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item (editable)"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.actionSubmenu_2.setText(_translate("MainWindow", "Submenu"))
        self.actionSubmenu_3.setText(_translate("MainWindow", "Submenu"))
        self.actionSUBSUB.setText(_translate("MainWindow", "SUBSUB"))
        self.actionSUBSUB_2.setText(_translate("MainWindow", "SUBSUB"))
        self.actionSUBSUB_3.setText(_translate("MainWindow", "SUBSUB"))
        self.actiondissabled.setText(_translate("MainWindow", "dissabled"))
        self.actionSubmenu.setText(_translate("MainWindow", "Submenu"))
        self.actionSubmenu_4.setText(_translate("MainWindow", "Submenu"))
        self.actionSubmenu_5.setText(_translate("MainWindow", "Submenu"))
        self.actionToolbar.setText(_translate("MainWindow", "Qt Material Theme"))
        self.actionToolbar.setToolTip(_translate("MainWindow", "Qt Material Theme"))
        self.actionSelected.setText(_translate("MainWindow", "Selected"))
        self.test_action.setText(_translate("MainWindow", "测试"))
        self.test_action_2.setText(_translate("MainWindow", "测试2"))
        self.actionaction3.setText(_translate("MainWindow", "action3"))
        self.action111.setText(_translate("MainWindow", "111"))
        self.action222.setText(_translate("MainWindow", "222"))
        self.action333.setText(_translate("MainWindow", "333"))
        self.actionsubmenu.setText(_translate("MainWindow", "New..."))
        self.actionsubmenu_2.setText(_translate("MainWindow", "Open..."))
        self.actionsubmenu_3.setText(_translate("MainWindow", "Save as..."))
        self.actionsubmenu_4.setText(_translate("MainWindow", "Save"))
        self.actionSave_all.setText(_translate("MainWindow", "Save all"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

