# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_3.setDocumentMode(True)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tab_down = QtWidgets.QTabWidget(self.tab_7)
        self.tab_down.setUsesScrollButtons(True)
        self.tab_down.setTabsClosable(True)
        self.tab_down.setObjectName("tab_down")
        self.com_tab_down = QtWidgets.QWidget()
        self.com_tab_down.setObjectName("com_tab_down")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.com_tab_down)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.com_tab_down)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        item.setIcon(icon)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(2, 2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.tableWidget, 0, 3, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.com_tab_down)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.gridLayout_6.addWidget(self.treeWidget, 0, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.com_tab_down)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_3 = QtWidgets.QSplitter(self.frame)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.frame_3 = QtWidgets.QFrame(self.splitter_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.frame_3)
        self.horizontalScrollBar_2.setProperty("value", 50)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.gridLayout_12.addWidget(self.horizontalScrollBar_2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.splitter_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider_2.setProperty("value", 50)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_15.addWidget(self.horizontalSlider_2, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.splitter_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.progressBar_2 = QtWidgets.QProgressBar(self.frame_5)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_19.addWidget(self.progressBar_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.page_5)
        self.verticalScrollBar_2.setProperty("value", 50)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.gridLayout_18.addWidget(self.verticalScrollBar_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(8, 108, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.page_5)
        self.verticalSlider_2.setProperty("value", 50)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.gridLayout_18.addWidget(self.verticalSlider_2, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem2, 0, 4, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.gridLayout_13.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.com_tab_down)
        self.listWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_2.setIconSize(QtCore.QSize(64, 64))
        self.listWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_2.setMovement(QtWidgets.QListView.Static)
        self.listWidget_2.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_2.setProperty("isWrapping", False)
        self.listWidget_2.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_2.setLayoutMode(QtWidgets.QListView.Batched)
        self.listWidget_2.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_2.setSelectionRectVisible(False)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.gridLayout_6.addWidget(self.listWidget_2, 0, 2, 1, 1)
        self.tab_down.addTab(self.com_tab_down, "")
        self.warning_tab_down = QtWidgets.QWidget()
        self.warning_tab_down.setObjectName("warning_tab_down")
        self.tab_down.addTab(self.warning_tab_down, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tab_15)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.widget = QtWidgets.QWidget(self.tab_15)
        self.widget.setObjectName("widget")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.gridLayout_29.addWidget(self.widget, 0, 0, 1, 1)
        self.tab_down.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.frame_6 = QtWidgets.QFrame(self.tab_16)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_30.addWidget(self.frame_6, 0, 0, 1, 1)
        self.tab_down.addTab(self.tab_16, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.tab_18)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_18)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        item.setIcon(icon)
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(2, 2, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_35.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tab_down.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.tab_19)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_19)
        self.groupBox_7.setCheckable(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_41.addWidget(self.pushButton_28, 0, 0, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_29.setFlat(True)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_41.addWidget(self.pushButton_29, 1, 1, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_41.addWidget(self.pushButton_30, 0, 2, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_31.setFlat(True)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_41.addWidget(self.pushButton_31, 1, 2, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_41.addWidget(self.pushButton_32, 0, 1, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_33.setFlat(True)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_41.addWidget(self.pushButton_33, 1, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_41, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_42.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_40.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.tab_down.addTab(self.tab_19, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget_5.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.tab_20)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_20)
        self.tabWidget_6.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab_22)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_22)
        self.tabWidget_7.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.tabWidget_7.addTab(self.tab_24, "")
        self.tab_38 = QtWidgets.QWidget()
        self.tab_38.setObjectName("tab_38")
        self.tabWidget_7.addTab(self.tab_38, "")
        self.tab_39 = QtWidgets.QWidget()
        self.tab_39.setObjectName("tab_39")
        self.tabWidget_7.addTab(self.tab_39, "")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.tabWidget_7.addTab(self.tab_25, "")
        self.gridLayout_28.addWidget(self.tabWidget_7, 0, 0, 1, 1)
        self.tabWidget_6.addTab(self.tab_22, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.tabWidget_6.addTab(self.tab_23, "")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.tabWidget_6.addTab(self.tab_28, "")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.tabWidget_6.addTab(self.tab_29, "")
        self.tab_30 = QtWidgets.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.tabWidget_6.addTab(self.tab_30, "")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.tabWidget_6.addTab(self.tab_31, "")
        self.tab_32 = QtWidgets.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.tabWidget_6.addTab(self.tab_32, "")
        self.tab_33 = QtWidgets.QWidget()
        self.tab_33.setObjectName("tab_33")
        self.tabWidget_6.addTab(self.tab_33, "")
        self.tab_34 = QtWidgets.QWidget()
        self.tab_34.setObjectName("tab_34")
        self.tabWidget_6.addTab(self.tab_34, "")
        self.tab_35 = QtWidgets.QWidget()
        self.tab_35.setObjectName("tab_35")
        self.tabWidget_6.addTab(self.tab_35, "")
        self.tab_36 = QtWidgets.QWidget()
        self.tab_36.setObjectName("tab_36")
        self.tabWidget_6.addTab(self.tab_36, "")
        self.tab_37 = QtWidgets.QWidget()
        self.tab_37.setObjectName("tab_37")
        self.tabWidget_6.addTab(self.tab_37, "")
        self.gridLayout_25.addWidget(self.tabWidget_6, 0, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_20, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.tabWidget_5.addTab(self.tab_26, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tabWidget_5.addTab(self.tab_21, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.tabWidget_5.addTab(self.tab_27, "")
        self.gridLayout_10.addWidget(self.tabWidget_5, 0, 0, 1, 1)
        self.tab_down.addTab(self.tab_6, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_14)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_43.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fontComboBox = QtWidgets.QFontComboBox(self.tab_14)
        self.fontComboBox.setObjectName("fontComboBox")
        self.verticalLayout_7.addWidget(self.fontComboBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.gridLayout_43.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_6.addWidget(self.lineEdit_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.gridLayout_43.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab_14)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_8.addWidget(self.spinBox_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.gridLayout_43.addLayout(self.verticalLayout_8, 0, 3, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.tab_14)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.gridLayout_43.addLayout(self.verticalLayout_9, 0, 4, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.tab_14)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.verticalLayout_10.addWidget(self.timeEdit_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.gridLayout_43.addLayout(self.verticalLayout_10, 0, 5, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_14)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.verticalLayout_11.addWidget(self.dateEdit_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.gridLayout_43.addLayout(self.verticalLayout_11, 0, 6, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.tab_14)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.verticalLayout_5.addWidget(self.dateTimeEdit_2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.gridLayout_43.addLayout(self.verticalLayout_5, 0, 7, 1, 1)
        self.tab_down.addTab(self.tab_14, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tab_down.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tab_down.addTab(self.tab_5, "")
        self.gridLayout_16.addWidget(self.tab_down, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.tab_17)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.frame_7 = QtWidgets.QFrame(self.tab_17)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtWidgets.QFrame(self.frame_7)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.line_3 = QtWidgets.QFrame(self.frame_7)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.line = QtWidgets.QFrame(self.frame_7)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout_33.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_4 = QtWidgets.QFrame(self.frame_7)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.line_5 = QtWidgets.QFrame(self.frame_7)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.line_6 = QtWidgets.QFrame(self.frame_7)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.gridLayout_33.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.gridLayout_33.setColumnStretch(0, 1)
        self.gridLayout_33.setColumnStretch(1, 1)
        self.gridLayout_31.addWidget(self.frame_7, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_17, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.gridLayout.addWidget(self.tabWidget_3, 1, 0, 1, 3)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tab_left = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_left.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tab_left.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_left.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_left.setObjectName("tab_left")
        self.com_tab = QtWidgets.QWidget()
        self.com_tab.setObjectName("com_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.com_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.com_tab)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.com_combo = QtWidgets.QComboBox(self.com_tab)
        self.com_combo.setObjectName("com_combo")
        self.verticalLayout_2.addWidget(self.com_combo)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.com_info_icon_label_new_connect = QtWidgets.QLabel(self.com_tab)
        self.com_info_icon_label_new_connect.setMinimumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label_new_connect.setMaximumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label_new_connect.setText("")
        self.com_info_icon_label_new_connect.setObjectName("com_info_icon_label_new_connect")
        self.horizontalLayout_5.addWidget(self.com_info_icon_label_new_connect)
        self.com_info_label_new_connect = QtWidgets.QLabel(self.com_tab)
        self.com_info_label_new_connect.setMaximumSize(QtCore.QSize(16777215, 16))
        self.com_info_label_new_connect.setText("")
        self.com_info_label_new_connect.setObjectName("com_info_label_new_connect")
        self.horizontalLayout_5.addWidget(self.com_info_label_new_connect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_17 = QtWidgets.QLabel(self.com_tab)
        self.label_17.setMinimumSize(QtCore.QSize(0, 20))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.baud_rate_combo = QtWidgets.QComboBox(self.com_tab)
        self.baud_rate_combo.setObjectName("baud_rate_combo")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.verticalLayout_2.addWidget(self.baud_rate_combo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.com_btn = QtWidgets.QPushButton(self.com_tab)
        self.com_btn.setObjectName("com_btn")
        self.verticalLayout.addWidget(self.com_btn)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.com_info_icon_label = QtWidgets.QLabel(self.com_tab)
        self.com_info_icon_label.setMinimumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label.setMaximumSize(QtCore.QSize(16, 16))
        self.com_info_icon_label.setText("")
        self.com_info_icon_label.setObjectName("com_info_icon_label")
        self.horizontalLayout_4.addWidget(self.com_info_icon_label)
        self.com_info_label = QtWidgets.QLabel(self.com_tab)
        self.com_info_label.setMaximumSize(QtCore.QSize(16777215, 16))
        self.com_info_label.setText("")
        self.com_info_label.setObjectName("com_info_label")
        self.horizontalLayout_4.addWidget(self.com_info_label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.groupBox_3 = QtWidgets.QGroupBox(self.com_tab)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tab_left.addTab(self.com_tab, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.tab_left.addTab(self.tab_13, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.data_type_btn_groupBox = QtWidgets.QGroupBox(self.tab_12)
        self.data_type_btn_groupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.data_type_btn_groupBox.setCheckable(False)
        self.data_type_btn_groupBox.setObjectName("data_type_btn_groupBox")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.data_type_btn_groupBox)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.data_type_btn_layout = QtWidgets.QVBoxLayout()
        self.data_type_btn_layout.setObjectName("data_type_btn_layout")
        self.gridLayout_38.addLayout(self.data_type_btn_layout, 0, 0, 1, 1)
        self.data_type_update_btn = QtWidgets.QPushButton(self.data_type_btn_groupBox)
        self.data_type_update_btn.setObjectName("data_type_update_btn")
        self.gridLayout_38.addWidget(self.data_type_update_btn, 1, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.data_type_btn_groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 26))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 26))
        self.textEdit_2.setStyleSheet("padding-top: 0px; padding-bottom: 0px;")
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_2.setAcceptRichText(False)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setMaximumSize(QtCore.QSize(26, 26))
        font = QtGui.QFont()
        font.setKerning(False)
        self.pushButton.setFont(font)
        self.pushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_36.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.groupBox_4)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        self.gridLayout_36.addWidget(self.treeWidget_2, 2, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.groupBox_4)
        self.tab_left.addTab(self.tab_12, "")
        self.gridLayout.addWidget(self.tab_left, 0, 1, 1, 1)
        self.tab_right = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_right.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_right.setTabsClosable(False)
        self.tab_right.setObjectName("tab_right")
        self.data_tab_right = QtWidgets.QWidget()
        self.data_tab_right.setObjectName("data_tab_right")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.data_tab_right)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.data_tab_right)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 543, 420))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.data_tab_right_gridLayout = QtWidgets.QGridLayout()
        self.data_tab_right_gridLayout.setObjectName("data_tab_right_gridLayout")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 1, 0, 1, 1)
        self.z3_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z3_lcd.setSmallDecimalPoint(True)
        self.z3_lcd.setDigitCount(10)
        self.z3_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z3_lcd.setProperty("value", 0.0)
        self.z3_lcd.setObjectName("z3_lcd")
        self.gridLayout_7.addWidget(self.z3_lcd, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 2, 0, 1, 1)
        self.y3_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y3_lcd.setSmallDecimalPoint(True)
        self.y3_lcd.setDigitCount(10)
        self.y3_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y3_lcd.setProperty("value", 0.0)
        self.y3_lcd.setObjectName("y3_lcd")
        self.gridLayout_7.addWidget(self.y3_lcd, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.x3_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x3_lcd.setSmallDecimalPoint(True)
        self.x3_lcd.setDigitCount(10)
        self.x3_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x3_lcd.setProperty("value", 0.0)
        self.x3_lcd.setObjectName("x3_lcd")
        self.gridLayout_7.addWidget(self.x3_lcd, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_7, 3, 0, 1, 1)
        self.gridLayout_data1 = QtWidgets.QGridLayout()
        self.gridLayout_data1.setObjectName("gridLayout_data1")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_data1.addWidget(self.label_7, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_data1.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_data1.addWidget(self.label_3, 1, 0, 1, 1)
        self.z1_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z1_lcd.setSmallDecimalPoint(True)
        self.z1_lcd.setDigitCount(10)
        self.z1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z1_lcd.setProperty("value", 0.0)
        self.z1_lcd.setObjectName("z1_lcd")
        self.gridLayout_data1.addWidget(self.z1_lcd, 2, 1, 1, 1)
        self.y1_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y1_lcd.setSmallDecimalPoint(True)
        self.y1_lcd.setDigitCount(10)
        self.y1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y1_lcd.setProperty("value", 0.0)
        self.y1_lcd.setObjectName("y1_lcd")
        self.gridLayout_data1.addWidget(self.y1_lcd, 1, 1, 1, 1)
        self.x1_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x1_lcd.setSmallDecimalPoint(True)
        self.x1_lcd.setDigitCount(10)
        self.x1_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x1_lcd.setProperty("value", 0.0)
        self.x1_lcd.setObjectName("x1_lcd")
        self.gridLayout_data1.addWidget(self.x1_lcd, 0, 1, 1, 1)
        self.gridLayout_data1.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_data1, 1, 0, 1, 1)
        self.data1_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data1_label.setObjectName("data1_label")
        self.data_tab_right_gridLayout.addWidget(self.data1_label, 0, 0, 1, 1)
        self.data2_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data2_label.setObjectName("data2_label")
        self.data_tab_right_gridLayout.addWidget(self.data2_label, 0, 1, 1, 1)
        self.data3_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data3_label.setObjectName("data3_label")
        self.data_tab_right_gridLayout.addWidget(self.data3_label, 2, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.x2_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x2_lcd.setSmallDecimalPoint(True)
        self.x2_lcd.setDigitCount(10)
        self.x2_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x2_lcd.setProperty("value", 0.0)
        self.x2_lcd.setObjectName("x2_lcd")
        self.gridLayout_14.addWidget(self.x2_lcd, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_14.addWidget(self.label_9, 1, 0, 1, 1)
        self.z2_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z2_lcd.setSmallDecimalPoint(True)
        self.z2_lcd.setDigitCount(10)
        self.z2_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z2_lcd.setProperty("value", 0.0)
        self.z2_lcd.setObjectName("z2_lcd")
        self.gridLayout_14.addWidget(self.z2_lcd, 2, 1, 1, 1)
        self.y2_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y2_lcd.setSmallDecimalPoint(True)
        self.y2_lcd.setDigitCount(10)
        self.y2_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y2_lcd.setProperty("value", 0.0)
        self.y2_lcd.setObjectName("y2_lcd")
        self.gridLayout_14.addWidget(self.y2_lcd, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_14.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_14.addWidget(self.label_10, 2, 0, 1, 1)
        self.gridLayout_14.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_14, 1, 1, 1, 1)
        self.data4_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.data4_label.setObjectName("data4_label")
        self.data_tab_right_gridLayout.addWidget(self.data4_label, 2, 1, 1, 1)
        self.gridLayout_data4 = QtWidgets.QGridLayout()
        self.gridLayout_data4.setObjectName("gridLayout_data4")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_data4.addWidget(self.label_13, 1, 0, 1, 1)
        self.z4_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.z4_lcd.setSmallDecimalPoint(True)
        self.z4_lcd.setDigitCount(10)
        self.z4_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.z4_lcd.setProperty("value", 0.0)
        self.z4_lcd.setObjectName("z4_lcd")
        self.gridLayout_data4.addWidget(self.z4_lcd, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_data4.addWidget(self.label_14, 2, 0, 1, 1)
        self.y4_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.y4_lcd.setSmallDecimalPoint(True)
        self.y4_lcd.setDigitCount(10)
        self.y4_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.y4_lcd.setProperty("value", 0.0)
        self.y4_lcd.setObjectName("y4_lcd")
        self.gridLayout_data4.addWidget(self.y4_lcd, 1, 1, 1, 1)
        self.x4_lcd = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.x4_lcd.setSmallDecimalPoint(True)
        self.x4_lcd.setDigitCount(10)
        self.x4_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.x4_lcd.setProperty("value", 0.0)
        self.x4_lcd.setObjectName("x4_lcd")
        self.gridLayout_data4.addWidget(self.x4_lcd, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_data4.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_data4.setColumnStretch(1, 2)
        self.data_tab_right_gridLayout.addLayout(self.gridLayout_data4, 3, 1, 1, 1)
        self.data_tab_right_gridLayout.setRowStretch(1, 1)
        self.data_tab_right_gridLayout.setRowStretch(3, 1)
        self.verticalLayout_15.addLayout(self.data_tab_right_gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tab_right.addTab(self.data_tab_right, "")
        self.graph_tab_right = QtWidgets.QWidget()
        self.graph_tab_right.setObjectName("graph_tab_right")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.graph_tab_right)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.graph_tab_time_scrollArea = QtWidgets.QScrollArea(self.graph_tab_right)
        self.graph_tab_time_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graph_tab_time_scrollArea.setWidgetResizable(True)
        self.graph_tab_time_scrollArea.setObjectName("graph_tab_time_scrollArea")
        self.graph_tab_right_layout = QtWidgets.QWidget()
        self.graph_tab_right_layout.setGeometry(QtCore.QRect(0, 0, 543, 420))
        self.graph_tab_right_layout.setObjectName("graph_tab_right_layout")
        self.graph_tab_time_scrollArea.setWidget(self.graph_tab_right_layout)
        self.verticalLayout_12.addWidget(self.graph_tab_time_scrollArea)
        self.tab_right.addTab(self.graph_tab_right, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.graph_tab_freq_scrollArea = QtWidgets.QScrollArea(self.tab)
        self.graph_tab_freq_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graph_tab_freq_scrollArea.setWidgetResizable(True)
        self.graph_tab_freq_scrollArea.setObjectName("graph_tab_freq_scrollArea")
        self.graph_tab_right_layout_2 = QtWidgets.QWidget()
        self.graph_tab_right_layout_2.setGeometry(QtCore.QRect(0, 0, 543, 420))
        self.graph_tab_right_layout_2.setObjectName("graph_tab_right_layout_2")
        self.graph_tab_freq_scrollArea.setWidget(self.graph_tab_right_layout_2)
        self.verticalLayout_13.addWidget(self.graph_tab_freq_scrollArea)
        self.tab_right.addTab(self.tab, "")
        self.vcom_tab_right = QtWidgets.QWidget()
        self.vcom_tab_right.setObjectName("vcom_tab_right")
        self.tab_right.addTab(self.vcom_tab_right, "")
        self.gridLayout.addWidget(self.tab_right, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_vertical = QtWidgets.QToolBar(MainWindow)
        self.toolBar_vertical.setObjectName("toolBar_vertical")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_vertical)
        self.help_dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.help_dockWidget.setObjectName("help_dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.textEdit = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_26.addWidget(self.textEdit, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_26.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.help_dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.help_dockWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1222, 24))
        self.menubar.setObjectName("menubar")
        self.menuStyles = QtWidgets.QMenu(self.menubar)
        self.menuStyles.setObjectName("menuStyles")
        self.menuMenu_with_icons = QtWidgets.QMenu(self.menubar)
        self.menuMenu_with_icons.setObjectName("menuMenu_with_icons")
        self.menumenu2 = QtWidgets.QMenu(self.menubar)
        self.menumenu2.setObjectName("menumenu2")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        self.menuSubmenu = QtWidgets.QMenu(self.menumenu)
        self.menuSubmenu.setObjectName("menuSubmenu")
        self.menuDensity = QtWidgets.QMenu(self.menubar)
        self.menuDensity.setObjectName("menuDensity")
        self.menuMenu3 = QtWidgets.QMenu(self.menubar)
        self.menuMenu3.setObjectName("menuMenu3")
        self.menumenu_disabled = QtWidgets.QMenu(self.menubar)
        self.menumenu_disabled.setEnabled(False)
        self.menumenu_disabled.setObjectName("menumenu_disabled")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_6 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_6.setEnabled(False)
        self.dockWidget_6.setMinimumSize(QtCore.QSize(0, 16))
        self.dockWidget_6.setMaximumSize(QtCore.QSize(0, 16))
        self.dockWidget_6.setObjectName("dockWidget_6")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.listWidget = QtWidgets.QListWidget(self.dockWidgetContents_5)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.listWidget.addItem(item)
        self.gridLayout_20.addWidget(self.listWidget, 0, 0, 1, 1)
        self.dockWidget_6.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_6)
        self.actionSubmenu_2 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_2.setCheckable(True)
        self.actionSubmenu_2.setObjectName("actionSubmenu_2")
        self.actionSubmenu_3 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_3.setObjectName("actionSubmenu_3")
        self.actionSUBSUB = QtWidgets.QAction(MainWindow)
        self.actionSUBSUB.setObjectName("actionSUBSUB")
        self.actionSUBSUB_2 = QtWidgets.QAction(MainWindow)
        self.actionSUBSUB_2.setObjectName("actionSUBSUB_2")
        self.actionSUBSUB_3 = QtWidgets.QAction(MainWindow)
        self.actionSUBSUB_3.setObjectName("actionSUBSUB_3")
        self.actiondissabled = QtWidgets.QAction(MainWindow)
        self.actiondissabled.setEnabled(False)
        self.actiondissabled.setObjectName("actiondissabled")
        self.actionSubmenu = QtWidgets.QAction(MainWindow)
        self.actionSubmenu.setCheckable(True)
        self.actionSubmenu.setChecked(True)
        self.actionSubmenu.setObjectName("actionSubmenu")
        self.actionSubmenu_4 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_4.setCheckable(True)
        self.actionSubmenu_4.setObjectName("actionSubmenu_4")
        self.actionSubmenu_5 = QtWidgets.QAction(MainWindow)
        self.actionSubmenu_5.setCheckable(True)
        self.actionSubmenu_5.setEnabled(False)
        self.actionSubmenu_5.setObjectName("actionSubmenu_5")
        self.actionToolbar = QtWidgets.QAction(MainWindow)
        self.actionToolbar.setObjectName("actionToolbar")
        self.actionSelected = QtWidgets.QAction(MainWindow)
        self.actionSelected.setCheckable(True)
        self.actionSelected.setChecked(True)
        self.actionSelected.setObjectName("actionSelected")
        self.test_action = QtWidgets.QAction(MainWindow)
        self.test_action.setObjectName("test_action")
        self.test_action_2 = QtWidgets.QAction(MainWindow)
        self.test_action_2.setObjectName("test_action_2")
        self.actionaction3 = QtWidgets.QAction(MainWindow)
        self.actionaction3.setObjectName("actionaction3")
        self.action111 = QtWidgets.QAction(MainWindow)
        self.action111.setCheckable(True)
        self.action111.setObjectName("action111")
        self.action222 = QtWidgets.QAction(MainWindow)
        self.action222.setCheckable(True)
        self.action222.setObjectName("action222")
        self.action333 = QtWidgets.QAction(MainWindow)
        self.action333.setCheckable(True)
        self.action333.setObjectName("action333")
        self.actionsubmenu = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionsubmenu.setIcon(icon)
        self.actionsubmenu.setObjectName("actionsubmenu")
        self.actionsubmenu_2 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("folder")
        self.actionsubmenu_2.setIcon(icon)
        self.actionsubmenu_2.setObjectName("actionsubmenu_2")
        self.actionsubmenu_3 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.actionsubmenu_3.setIcon(icon)
        self.actionsubmenu_3.setObjectName("actionsubmenu_3")
        self.actionsubmenu_4 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionsubmenu_4.setIcon(icon)
        self.actionsubmenu_4.setObjectName("actionsubmenu_4")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.actionClose.setIcon(icon)
        self.actionClose.setObjectName("actionClose")
        self.toolBar.addAction(self.actionToolbar)
        self.toolBar.addAction(self.actionSelected)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.test_action)
        self.toolBar.addAction(self.test_action_2)
        self.toolBar.addAction(self.actionaction3)
        self.toolBar_vertical.addAction(self.actionToolbar)
        self.toolBar_vertical.addAction(self.actionSelected)
        self.menuMenu_with_icons.addAction(self.actionsubmenu)
        self.menuMenu_with_icons.addAction(self.actionsubmenu_2)
        self.menuMenu_with_icons.addSeparator()
        self.menuMenu_with_icons.addAction(self.actionsubmenu_4)
        self.menuMenu_with_icons.addAction(self.actionsubmenu_3)
        self.menuMenu_with_icons.addAction(self.actionSave_all)
        self.menuMenu_with_icons.addSeparator()
        self.menuMenu_with_icons.addAction(self.actionClose)
        self.menumenu2.addAction(self.actionSubmenu)
        self.menumenu2.addAction(self.actionSubmenu_4)
        self.menumenu2.addAction(self.actionSubmenu_5)
        self.menuSubmenu.addAction(self.actionSUBSUB)
        self.menuSubmenu.addAction(self.actionSUBSUB_2)
        self.menuSubmenu.addSeparator()
        self.menuSubmenu.addAction(self.actionSUBSUB_3)
        self.menumenu.addAction(self.menuSubmenu.menuAction())
        self.menumenu.addAction(self.actionSubmenu_2)
        self.menumenu.addSeparator()
        self.menumenu.addAction(self.actionSubmenu_3)
        self.menumenu.addAction(self.actiondissabled)
        self.menubar.addAction(self.menuDensity.menuAction())
        self.menubar.addAction(self.menumenu.menuAction())
        self.menubar.addAction(self.menumenu2.menuAction())
        self.menubar.addAction(self.menuMenu_with_icons.menuAction())
        self.menubar.addAction(self.menumenu_disabled.menuAction())
        self.menubar.addAction(self.menuMenu3.menuAction())
        self.menubar.addAction(self.menuStyles.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(0)
        self.tab_down.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tab_left.setCurrentIndex(2)
        self.tab_right.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tab_left, self.groupBox_3)
        MainWindow.setTabOrder(self.groupBox_3, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.tabWidget_3)
        MainWindow.setTabOrder(self.tabWidget_3, self.tab_down)
        MainWindow.setTabOrder(self.tab_down, self.horizontalSlider_2)
        MainWindow.setTabOrder(self.horizontalSlider_2, self.verticalSlider_2)
        MainWindow.setTabOrder(self.verticalSlider_2, self.treeWidget)
        MainWindow.setTabOrder(self.treeWidget, self.listWidget_2)
        MainWindow.setTabOrder(self.listWidget_2, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.tab_right)
        MainWindow.setTabOrder(self.tab_right, self.dateEdit_2)
        MainWindow.setTabOrder(self.dateEdit_2, self.listWidget)
        MainWindow.setTabOrder(self.listWidget, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.groupBox_7)
        MainWindow.setTabOrder(self.groupBox_7, self.pushButton_28)
        MainWindow.setTabOrder(self.pushButton_28, self.pushButton_32)
        MainWindow.setTabOrder(self.pushButton_32, self.pushButton_30)
        MainWindow.setTabOrder(self.pushButton_30, self.pushButton_33)
        MainWindow.setTabOrder(self.pushButton_33, self.pushButton_29)
        MainWindow.setTabOrder(self.pushButton_29, self.pushButton_31)
        MainWindow.setTabOrder(self.pushButton_31, self.doubleSpinBox_3)
        MainWindow.setTabOrder(self.doubleSpinBox_3, self.timeEdit_2)
        MainWindow.setTabOrder(self.timeEdit_2, self.dateTimeEdit_2)
        MainWindow.setTabOrder(self.dateTimeEdit_2, self.comboBox_8)
        MainWindow.setTabOrder(self.comboBox_8, self.tabWidget_6)
        MainWindow.setTabOrder(self.tabWidget_6, self.fontComboBox)
        MainWindow.setTabOrder(self.fontComboBox, self.tabWidget_5)
        MainWindow.setTabOrder(self.tabWidget_5, self.tabWidget_7)
        MainWindow.setTabOrder(self.tabWidget_7, self.spinBox_3)
        MainWindow.setTabOrder(self.spinBox_3, self.tableWidget_2)
        MainWindow.setTabOrder(self.tableWidget_2, self.lineEdit_5)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qt Material"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row-1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Row-3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Datetime"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "00:05:02"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "2020-04-27 17:31:34"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Unamed-1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "00:01:02"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "2020-04-27 17:31:34"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "Unamed-2"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "00:07:02"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "2020-04-27 17:31:34"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "Unamed-3"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Material Tree"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Tree #1"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Subitem #1"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Subitem #2"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Tree #2"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Subitem #4"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Subitem #41"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Subitem #42"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Subitem #5"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Tree #3"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "Tree #4"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.listWidget_2.setSortingEnabled(True)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tab_down.setTabText(self.tab_down.indexOf(self.com_tab_down), _translate("MainWindow", "串口"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.warning_tab_down), _translate("MainWindow", "警告"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_15), _translate("MainWindow", "Widget area"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_16), _translate("MainWindow", "Frame area"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row-1"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Row-3"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Datetime"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "00:05:02"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "2020-04-27 17:31:34"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "Unamed-1"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "00:01:02"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "2020-04-27 17:31:34"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "Unamed-2"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "00:07:02"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "2020-04-27 17:31:34"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("MainWindow", "Unamed-3"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_18), _translate("MainWindow", "Table"))
        self.groupBox_7.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_28.setText(_translate("MainWindow", "Danger"))
        self.pushButton_28.setProperty("class", _translate("MainWindow", "danger"))
        self.pushButton_29.setText(_translate("MainWindow", "Success"))
        self.pushButton_29.setProperty("class", _translate("MainWindow", "success"))
        self.pushButton_30.setText(_translate("MainWindow", "Warning"))
        self.pushButton_30.setProperty("class", _translate("MainWindow", "warning"))
        self.pushButton_31.setText(_translate("MainWindow", "Warning"))
        self.pushButton_31.setProperty("class", _translate("MainWindow", "warning"))
        self.pushButton_32.setText(_translate("MainWindow", "Success"))
        self.pushButton_32.setProperty("class", _translate("MainWindow", "success"))
        self.pushButton_33.setText(_translate("MainWindow", "Danger"))
        self.pushButton_33.setProperty("class", _translate("MainWindow", "danger"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_19), _translate("MainWindow", "Buttons colored"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_24), _translate("MainWindow", "Tab 1"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_38), _translate("MainWindow", "Page"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_39), _translate("MainWindow", "Page"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_25), _translate("MainWindow", "Tab 2"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_22), _translate("MainWindow", "Tab 1"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_23), _translate("MainWindow", "Tab 2"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_28), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_29), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_30), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_31), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_32), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_33), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_34), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_35), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_36), _translate("MainWindow", "Page"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_37), _translate("MainWindow", "Page"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_20), _translate("MainWindow", "Tab 1"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_26), _translate("MainWindow", "Page"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_21), _translate("MainWindow", "Tab 2"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_27), _translate("MainWindow", "Page"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_6), _translate("MainWindow", "Tabs"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "New Item"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "New Item"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "New Item"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_14), _translate("MainWindow", "Inputs"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.tab_down.setTabText(self.tab_down.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Page"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_17), _translate("MainWindow", "Lines"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Page"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Page"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Long Page Name"))
        self.label_18.setText(_translate("MainWindow", "端口号"))
        self.label_17.setText(_translate("MainWindow", "波特率"))
        self.baud_rate_combo.setItemText(0, _translate("MainWindow", "2400"))
        self.baud_rate_combo.setItemText(1, _translate("MainWindow", "4800"))
        self.baud_rate_combo.setItemText(2, _translate("MainWindow", "9600"))
        self.baud_rate_combo.setItemText(3, _translate("MainWindow", "19200"))
        self.baud_rate_combo.setItemText(4, _translate("MainWindow", "38400"))
        self.baud_rate_combo.setItemText(5, _translate("MainWindow", "57600"))
        self.baud_rate_combo.setItemText(6, _translate("MainWindow", "115200"))
        self.baud_rate_combo.setItemText(7, _translate("MainWindow", "230400"))
        self.com_btn.setText(_translate("MainWindow", "启动"))
        self.groupBox_3.setTitle(_translate("MainWindow", "串口设置"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.tab_left.setTabText(self.tab_left.indexOf(self.com_tab), _translate("MainWindow", "串口"))
        self.tab_left.setTabText(self.tab_left.indexOf(self.tab_13), _translate("MainWindow", "配置"))
        self.data_type_btn_groupBox.setTitle(_translate("MainWindow", "数据类型"))
        self.data_type_btn_groupBox.setProperty("class", _translate("MainWindow", "fill_background"))
        self.data_type_update_btn.setText(_translate("MainWindow", "更新"))
        self.groupBox_4.setTitle(_translate("MainWindow", "待选数据类型"))
        self.groupBox_4.setProperty("class", _translate("MainWindow", "fill_background"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "Material Tree"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("MainWindow", "Tree #1"))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Subitem #1"))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Subitem #2"))
        self.treeWidget_2.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.treeWidget_2.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "New Item"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("MainWindow", "Tree #2"))
        self.treeWidget_2.topLevelItem(2).setText(0, _translate("MainWindow", "Subitem #4"))
        self.treeWidget_2.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Subitem #41"))
        self.treeWidget_2.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Subitem #42"))
        self.treeWidget_2.topLevelItem(3).setText(0, _translate("MainWindow", "Subitem #5"))
        self.treeWidget_2.topLevelItem(4).setText(0, _translate("MainWindow", "Tree #3"))
        self.treeWidget_2.topLevelItem(5).setText(0, _translate("MainWindow", "Tree #4"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.tab_left.setTabText(self.tab_left.indexOf(self.tab_12), _translate("MainWindow", "数据"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.label_6.setText(_translate("MainWindow", "X"))
        self.label_7.setText(_translate("MainWindow", "Z"))
        self.label.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Z"))
        self.data1_label.setText(_translate("MainWindow", "data1"))
        self.data2_label.setText(_translate("MainWindow", "data2"))
        self.data3_label.setText(_translate("MainWindow", "data3"))
        self.label_9.setText(_translate("MainWindow", "Y"))
        self.label_11.setText(_translate("MainWindow", "X"))
        self.label_10.setText(_translate("MainWindow", "Z"))
        self.data4_label.setText(_translate("MainWindow", "data4"))
        self.label_13.setText(_translate("MainWindow", "Y"))
        self.label_14.setText(_translate("MainWindow", "Z"))
        self.label_15.setText(_translate("MainWindow", "X"))
        self.tab_right.setTabText(self.tab_right.indexOf(self.data_tab_right), _translate("MainWindow", "实时监视"))
        self.tab_right.setTabText(self.tab_right.indexOf(self.graph_tab_right), _translate("MainWindow", "时域"))
        self.tab_right.setTabText(self.tab_right.indexOf(self.tab), _translate("MainWindow", "频域"))
        self.tab_right.setTabText(self.tab_right.indexOf(self.vcom_tab_right), _translate("MainWindow", "模拟单片机"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_vertical.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.help_dockWidget.setWindowTitle(_translate("MainWindow", "说明书"))
        self.textEdit.setMarkdown(_translate("MainWindow", "欢迎使用上位机\n"
"\n"
""))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">欢迎使用上位机</p></body></html>"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "请配置串口"))
        self.menuStyles.setTitle(_translate("MainWindow", "风格"))
        self.menuMenu_with_icons.setTitle(_translate("MainWindow", "Menu with icons"))
        self.menumenu2.setTitle(_translate("MainWindow", "Menu2"))
        self.menumenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuSubmenu.setTitle(_translate("MainWindow", "Submenu"))
        self.menuDensity.setTitle(_translate("MainWindow", "Density"))
        self.menuMenu3.setTitle(_translate("MainWindow", "Menu4"))
        self.menumenu_disabled.setTitle(_translate("MainWindow", "Menu3 disabled"))
        self.dockWidget_6.setWindowTitle(_translate("MainWindow", "Top Dock"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item (editable)"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.actionSubmenu_2.setText(_translate("MainWindow", "Submenu"))
        self.actionSubmenu_3.setText(_translate("MainWindow", "Submenu"))
        self.actionSUBSUB.setText(_translate("MainWindow", "SUBSUB"))
        self.actionSUBSUB_2.setText(_translate("MainWindow", "SUBSUB"))
        self.actionSUBSUB_3.setText(_translate("MainWindow", "SUBSUB"))
        self.actiondissabled.setText(_translate("MainWindow", "dissabled"))
        self.actionSubmenu.setText(_translate("MainWindow", "Submenu"))
        self.actionSubmenu_4.setText(_translate("MainWindow", "Submenu"))
        self.actionSubmenu_5.setText(_translate("MainWindow", "Submenu"))
        self.actionToolbar.setText(_translate("MainWindow", "Qt Material Theme"))
        self.actionToolbar.setToolTip(_translate("MainWindow", "Qt Material Theme"))
        self.actionSelected.setText(_translate("MainWindow", "Selected"))
        self.test_action.setText(_translate("MainWindow", "测试"))
        self.test_action_2.setText(_translate("MainWindow", "测试2"))
        self.actionaction3.setText(_translate("MainWindow", "action3"))
        self.action111.setText(_translate("MainWindow", "111"))
        self.action222.setText(_translate("MainWindow", "222"))
        self.action333.setText(_translate("MainWindow", "333"))
        self.actionsubmenu.setText(_translate("MainWindow", "New..."))
        self.actionsubmenu_2.setText(_translate("MainWindow", "Open..."))
        self.actionsubmenu_3.setText(_translate("MainWindow", "Save as..."))
        self.actionsubmenu_4.setText(_translate("MainWindow", "Save"))
        self.actionSave_all.setText(_translate("MainWindow", "Save all"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

