# -*- coding: utf-8 -*-
# @Time    : 2023/4/26 16:21
# @Author  : XXX
# @Site    : 
# @File    : data_type_db.py
# @Software: PyCharm 
# @Comment :
import numpy as np

DATA_TYPE_DB = [
    {'name': '速度-RMS均', 'is_v': 'V', 'address': [0, 1, 2], 'mult': 100, 'show_freq': True},
    {'name': '温度', 'is_v': 'S', 'address': [3], 'mult': 100, 'show_freq': False},
    {'name': '加速度-RMS均', 'is_v': 'V', 'address': [4, 5, 6], 'mult': 100, 'show_freq': True},
    {'name': '速度-MAX峰', 'is_v': 'V', 'address': [7, 11, 15], 'mult': 100, 'show_freq': True},
    {'name': '速度-峭度均', 'is_v': 'V', 'address': [8, 12, 16], 'mult': 100, 'show_freq': True},
    {'name': '加速度-MAX峰', 'is_v': 'V', 'address': [9, 13, 17], 'mult': 100, 'show_freq': True},
    {'name': '加速度-峭度均', 'is_v': 'V', 'address': [10, 14, 18], 'mult': 100, 'show_freq': True},
    {'name': '位移-峰峰值', 'is_v': 'V', 'address': [19, 20, 21], 'mult': 100, 'show_freq': True},
    {'name': '频谱分析周期计数', 'is_v': 'S', 'address': [22], 'mult': 1, 'show_freq': False},
    {'name': 'X震动通道ID', 'is_v': 'S', 'address': [23], 'mult': 1, 'show_freq': False},
    {'name': 'X该测点转速', 'is_v': 'S', 'address': [24], 'mult': 100},
    {'name': 'X内圈特征值1X', 'is_v': 'S', 'address': [25], 'mult': 100},
    {'name': 'X外圈特征值1X', 'is_v': 'S', 'address': [26], 'mult': 100},
    {'name': 'X滚动体特征值1X', 'is_v': 'S', 'address': [27], 'mult': 100},
    {'name': 'X保持架特征值1X', 'is_v': 'S', 'address': [28], 'mult': 100},
    {'name': 'X关注点1加速度谱能量', 'is_v': 'S', 'address': [29], 'mult': 100},
    {'name': 'X关注点2加速度谱能量', 'is_v': 'S', 'address': [30], 'mult': 100},
    {'name': 'X关注点3加速度谱能量', 'is_v': 'S', 'address': [31], 'mult': 100},
    {'name': 'X关注点4加速度谱能量', 'is_v': 'S', 'address': [32], 'mult': 100},
    {'name': 'X关注点5加速度谱能量', 'is_v': 'S', 'address': [33], 'mult': 100},
    {'name': 'X关注点6加速度谱能量', 'is_v': 'S', 'address': [34], 'mult': 100},
    {'name': 'X关注点7加速度谱能量', 'is_v': 'S', 'address': [35], 'mult': 100},
    {'name': 'X关注点8加速度谱能量', 'is_v': 'S', 'address': [36], 'mult': 100},
    {'name': 'X关注带1加速度谱能量', 'is_v': 'S', 'address': [37], 'mult': 100},
    {'name': 'X关注带2加速度谱能量', 'is_v': 'S', 'address': [38], 'mult': 100},
    {'name': 'X关注带3加速度谱能量', 'is_v': 'S', 'address': [39], 'mult': 100},
    {'name': 'X关注带4加速度谱能量', 'is_v': 'S', 'address': [40], 'mult': 100},
    {'name': 'X关注带5加速度谱能量', 'is_v': 'S', 'address': [41], 'mult': 100},
    {'name': 'X加速度谱最高能量点的阶次', 'is_v': 'S', 'address': [42], 'mult': 10},
    {'name': 'X加速度谱总能量', 'is_v': 'S', 'address': [43], 'mult': 100},
    {'name': 'X叶片特征值1X', 'is_v': 'S', 'address': [44], 'mult': 100},
    {'name': 'X叶片特征值2X', 'is_v': 'S', 'address': [45], 'mult': 100},
    {'name': 'X叶片特征值3X', 'is_v': 'S', 'address': [46], 'mult': 100},
    {'name': 'X叶片特征值4X', 'is_v': 'S', 'address': [47], 'mult': 100},
    {'name': 'X关注点1速度谱能量', 'is_v': 'S', 'address': [48], 'mult': 100},
    {'name': 'X关注点2速度谱能量', 'is_v': 'S', 'address': [49], 'mult': 100},
    {'name': 'X关注点3速度谱能量', 'is_v': 'S', 'address': [50], 'mult': 100},
    {'name': 'X关注点4速度谱能量', 'is_v': 'S', 'address': [51], 'mult': 100},
    {'name': 'X关注点5速度谱能量', 'is_v': 'S', 'address': [52], 'mult': 100},
    {'name': 'X关注点6速度谱能量', 'is_v': 'S', 'address': [53], 'mult': 100},
    {'name': 'X关注点7速度谱能量', 'is_v': 'S', 'address': [54], 'mult': 100},
    {'name': 'X关注点8速度谱能量', 'is_v': 'S', 'address': [55], 'mult': 100},
    {'name': 'X关注带1速度谱能量', 'is_v': 'S', 'address': [56], 'mult': 100},
    {'name': 'X关注带2速度谱能量', 'is_v': 'S', 'address': [57], 'mult': 100},
    {'name': 'X关注带3速度谱能量', 'is_v': 'S', 'address': [58], 'mult': 100},
    {'name': 'X关注带4速度谱能量', 'is_v': 'S', 'address': [59], 'mult': 100},
    {'name': 'X关注带5速度谱能量', 'is_v': 'S', 'address': [60], 'mult': 100},
    {'name': 'X速度谱最高能量点的阶次', 'is_v': 'S', 'address': [61], 'mult': 10},
    {'name': 'X速度谱总能量', 'is_v': 'S', 'address': [62], 'mult': 100},
    {'name': 'Y震动通道ID', 'is_v': 'S', 'address': [63], 'mult': 1, 'show_freq': False},
    {'name': 'Y该测点转速', 'is_v': 'S', 'address': [64], 'mult': 100},
    {'name': 'Y内圈特征值1X', 'is_v': 'S', 'address': [65], 'mult': 100},
    {'name': 'Y外圈特征值1X', 'is_v': 'S', 'address': [66], 'mult': 100},
    {'name': 'Y滚动体特征值1X', 'is_v': 'S', 'address': [67], 'mult': 100},
    {'name': 'Y保持架特征值1X', 'is_v': 'S', 'address': [68], 'mult': 100},
    {'name': 'Y关注点1加速度谱能量', 'is_v': 'S', 'address': [69], 'mult': 100},
    {'name': 'Y关注点2加速度谱能量', 'is_v': 'S', 'address': [70], 'mult': 100},
    {'name': 'Y关注点3加速度谱能量', 'is_v': 'S', 'address': [71], 'mult': 100},
    {'name': 'Y关注点4加速度谱能量', 'is_v': 'S', 'address': [72], 'mult': 100},
    {'name': 'Y关注点5加速度谱能量', 'is_v': 'S', 'address': [73], 'mult': 100},
    {'name': 'Y关注点6加速度谱能量', 'is_v': 'S', 'address': [74], 'mult': 100},
    {'name': 'Y关注点7加速度谱能量', 'is_v': 'S', 'address': [75], 'mult': 100},
    {'name': 'Y关注点8加速度谱能量', 'is_v': 'S', 'address': [76], 'mult': 100},
    {'name': 'Y关注带1加速度谱能量', 'is_v': 'S', 'address': [77], 'mult': 100},
    {'name': 'Y关注带2加速度谱能量', 'is_v': 'S', 'address': [78], 'mult': 100},
    {'name': 'Y关注带3加速度谱能量', 'is_v': 'S', 'address': [79], 'mult': 100},
    {'name': 'Y关注带4加速度谱能量', 'is_v': 'S', 'address': [80], 'mult': 100},
    {'name': 'Y关注带5加速度谱能量', 'is_v': 'S', 'address': [81], 'mult': 100},
    {'name': 'Y加速度谱最高能量点的阶次', 'is_v': 'S', 'address': [82], 'mult': 10},
    {'name': 'Y加速度谱总能量', 'is_v': 'S', 'address': [83], 'mult': 100},
    {'name': 'Y叶片特征值1X', 'is_v': 'S', 'address': [84], 'mult': 100},
    {'name': 'Y叶片特征值2X', 'is_v': 'S', 'address': [85], 'mult': 100},
    {'name': 'Y叶片特征值3X', 'is_v': 'S', 'address': [86], 'mult': 100},
    {'name': 'Y叶片特征值4X', 'is_v': 'S', 'address': [87], 'mult': 100},
    {'name': 'Y关注点1速度谱能量', 'is_v': 'S', 'address': [88], 'mult': 100},
    {'name': 'Y关注点2速度谱能量', 'is_v': 'S', 'address': [89], 'mult': 100},
    {'name': 'Y关注点3速度谱能量', 'is_v': 'S', 'address': [90], 'mult': 100},
    {'name': 'Y关注点4速度谱能量', 'is_v': 'S', 'address': [91], 'mult': 100},
    {'name': 'Y关注点5速度谱能量', 'is_v': 'S', 'address': [92], 'mult': 100},
    {'name': 'Y关注点6速度谱能量', 'is_v': 'S', 'address': [93], 'mult': 100},
    {'name': 'Y关注点7速度谱能量', 'is_v': 'S', 'address': [94], 'mult': 100},
    {'name': 'Y关注点8速度谱能量', 'is_v': 'S', 'address': [95], 'mult': 100},
    {'name': 'Y关注带1速度谱能量', 'is_v': 'S', 'address': [96], 'mult': 100},
    {'name': 'Y关注带2速度谱能量', 'is_v': 'S', 'address': [97], 'mult': 100},
    {'name': 'Y关注带3速度谱能量', 'is_v': 'S', 'address': [98], 'mult': 100},
    {'name': 'Y关注带4速度谱能量', 'is_v': 'S', 'address': [99], 'mult': 100},
    {'name': 'Y关注带5速度谱能量', 'is_v': 'S', 'address': [100], 'mult': 100},
    {'name': 'Y速度谱最高能量点的阶次', 'is_v': 'S', 'address': [101], 'mult': 10},
    {'name': 'Y速度谱总能量', 'is_v': 'S', 'address': [102], 'mult': 100},
    ]

DATA_TYPE_IDX = {dt['name']: i for i, dt in enumerate(DATA_TYPE_DB)}


def get_data_type_from_name(name: str):
    # TODO 异常值处理
    return DATA_TYPE_DB[DATA_TYPE_IDX[name]]
